[package]
name = "court_of_justice_public_front"
version = "0.1.0"
authors = ["andrejfilipov"]
edition = "2018"

crate-type = "cdylib"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.12.0"
yew-router = "0.9.0"