version: '3.2'

services:
  events-app-profile:
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - internal

networks:
  internal:
    external: false